# Generated by Django 2.2.2 on 2022-09-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(max_length=50)),
                ('modeleapi', models.CharField(max_length=128)),
                ('mkadrress', models.CharField(max_length=128)),
                ('retsuccess', models.TextField(help_text='success数据')),
                ('retfail', models.TextField(help_text='失败数据', null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lstuptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pms',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'mock_pms',
            },
        ),
        migrations.CreateModel(
            name='MockOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(help_text='配置项目名称', max_length=128)),
                ('stat', models.SmallIntegerField(choices=[(0, '启用'), (1, '禁止')], help_text='是否启用mock功能')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lstuptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MockOption',
                'verbose_name_plural': 'MockOption',
                'db_table': 'MockOption',
            },
        ),
    ]
