# Generated by Django 2.2.2 on 2022-09-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apidetail',
            table='ApiDetail',
        ),
    ]
